-- CreateEnum
CREATE TYPE "TransactionType" AS ENUM ('DEPOSIT', 'EXPENSE', 'INVESTMENT');

-- CreateEnum
CREATE TYPE "TransactionCategory" AS ENUM ('HOUSING', 'RENT', 'MORTGAGE', 'HOME_INSURANCE', 'HOME_MAINTENANCE', 'FURNITURE', 'TRANSPORTATION', 'FUEL', 'CAR_MAINTENANCE', 'PUBLIC_TRANSPORT', 'PARKING', 'CAR_INSURANCE', 'RIDE_SHARING', 'FOOD', 'GROCERIES', 'RESTAURANTS', 'DELIVERY', 'SNACKS', 'ENTERTAINMENT', 'STREAMING_SERVICES', 'GAMES', 'MOVIES', 'SPORTS', 'HOBBIES', 'TRAVEL', 'HEALTH', 'MEDICAL_INSURANCE', 'PHARMACY', 'DOCTOR', 'DENTAL', 'FITNESS', 'UTILITY', 'ELECTRICITY', 'WATER', 'GAS', 'INTERNET', 'PHONE', 'SALARY', 'BONUS', 'FREELANCE', 'INVESTMENTS_RETURN', 'RENTAL_INCOME', 'EDUCATION', 'TUITION', 'BOOKS', 'COURSES', 'SCHOOL_SUPPLIES', 'CREDIT_CARD', 'LOAN_PAYMENT', 'SAVINGS', 'INVESTMENTS', 'INSURANCE', 'TAXES', 'CLOTHING', 'PERSONAL_CARE', 'GIFTS', 'DONATIONS', 'PETS', 'BUSINESS_EXPENSES', 'OFFICE_SUPPLIES', 'MARKETING', 'SOFTWARE_SERVICES', 'OTHER', 'MISCELLANEOUS');

-- CreateEnum
CREATE TYPE "TransactionPaymentMethod" AS ENUM ('CREDIT_CARD', 'DEBIT_CARD', 'BANK_TRANSFER', 'BANK_SLIP', 'CASH', 'PIX', 'OTHER');

-- CreateTable
CREATE TABLE "Transaction" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "type" "TransactionType" NOT NULL,
    "amount" DECIMAL(10,2) NOT NULL,
    "category" "TransactionCategory" NOT NULL,
    "paymentMethod" "TransactionPaymentMethod" NOT NULL,
    "date" TIMESTAMP(3) NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "Transaction_pkey" PRIMARY KEY ("id")
);
